---
title: "Phecode_UKB"
author: "Jinhee Chang"
date: "12/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
phecode_ukb <- readr::read_tsv('phecode-ukbb-agg.tsv')
phecode_ukb$phecode <- sprintf("%.2f", phecode_ukb$phecode)
```

```{r}
source("Automated_functioncode.R")

for (i in (1:length(phecode_ukb$phecode))) {
  dataplotting(normalized_phecode(phecode_ukb$phecode[i]), NULL)
}
```

```{r}
source("Automated_functioncode.R")

clustering_preprocess <- function(func_name, code_num, age_cut = NULL) {
  
  clust_result <- totalage_freq[,c(1,3)]

  temp_result <- lapply(c(1:length(code_num)), function(i) {
    temp_list <- func_name(code_num[i])
    temp_df <- subset(temp_list[[1]],
                      temp_list[[1]]$category != "Total Disease(n=3003823)")
    colnames(temp_df)[3] <- temp_list[[2]]
    
    return(temp_df)
  })
  
  for (i in 1:length(temp_result)) {
    if (is.null(temp_result[[i]])) {
      next
      }
    temp <- temp_result[[i]][,c(1,3)]
    clust_result <- merge(clust_result, temp, by = "Age at Diagnosis", all = TRUE)
  }

  clust_result[,2] <- NULL
  row.names(clust_result) <- clust_result[,1]
  clust_result[,1] <- NULL
  
  clust_result <- as.matrix(clust_result)
  clust_result[is.na(clust_result)] <- 0
  
  if (!is.null(age_cut)) {
    max_age <- apply(clust_result, 2, which.max)
    clust_result_1 <- 
      clust_result[, as.numeric(rownames(clust_result)[max_age]) >= age_cut]
    }
  
  return(clust_result)
}

clust_result_2 <- clustering_preprocess(normalized_phecode, phecode_ukb$phecode, 60)
clust_result_3 <- clustering_preprocess(normalized_phecode, phecode_ukb$phecode, 75)

e <- apply(clust_result, 2, which.max)
e_age <- rownames(clust_result)[e]
e_age <- as.numeric(e_age)
clust_result_1 <- clust_result[, e_age >= 60]
```

```{r}
library("ComplexHeatmap")

library(circlize)
col_fun = colorRamp2(c(0, 1, 2, 4), c("white", "green", "yellow", "red"))

Heatmap(clust_result, cluster_rows = FALSE, col = col_fun)
Heatmap(c, cluster_rows = FALSE, col = col_fun)
Heatmap(clust_result_1 , cluster_rows = FALSE, col = col_fun)
Heatmap(clust_result_1, cluster_rows = FALSE, col = col_fun, column_split = 8)
```

```{r}
unique_category <- unique(phecode_ukb$category)

category_phecode = list()
for (i in 1:length(unique_category)) {
  
  category_phecode[[i]] <- as.data.frame(subset(phecode_ukb, category ==
                                                  unique_category[i])[,1])
}

source("Automated_functioncode.R")

category_result = list()
for (i in 1:length(unique_category)) {
  category_result[[i]] <- multi_normalized_phecode(category_phecode[[i]]$phecode,
                                                   unique_category[i])
}
dataplotting(category_result[[1]], NULL)

dataplotting(multi_normalized_phecode(category_phecode[[18]]$phecode, unique_category[18]), NULL)
```
